/* Generated By:JavaCC: Do not edit this line. PointerGrammarConstants.java */
package org.xbrlapi.xpointer;

public interface PointerGrammarConstants {

  int EOF = 0;
  int NormalChar = 2;
  int LeftDataBracket = 3;
  int RightBracket = 4;
  int EscapedChar = 5;
  int NCName = 6;
  int LeftBracket = 7;
  int NCNameChar = 8;
  int Letter = 9;
  int BaseChar = 10;
  int Ideographic = 11;
  int CombiningChar = 12;
  int Digit = 13;
  int Extender = 14;
  int Space = 15;

  int DEFAULT = 0;
  int WithinSchemeData = 1;

  String[] tokenImage = {
    "<EOF>",
    "\":\"",
    "<NormalChar>",
    "\"(\"",
    "\")\"",
    "<EscapedChar>",
    "<NCName>",
    "\"(\"",
    "<NCNameChar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
    "<Space>",
  };

}
